version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:16.13.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Eslint
          command: npm run lint
      - run:
          name: Running tests
          command: npm run test
      - sonarcloud/scan
      - run:
          name: Build the app
          command: CI=true npm run build

orbs:
  sonarcloud: sonarsource/sonarcloud@1.1.1

workflows:
  version: 2
  ci:
    jobs:
      - build:
          context: SonarCloud
