version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14.10.1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Lint the code
          command: npm run lint
      - run:
          name: Running tests
          command: npm run test
      - run:
          name: Scan code with Sonar
          command: sonarcloud/scan
      - run:
          name: Build the app
          command: CI=true npm run build

orbs:
  sonarcloud: sonarsource/sonarcloud@1.1.1

workflows:
  version: 2
  ci:
    jobs:
      - build
