version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14.10.1
    steps:
      - checkout
      - run: echo "npm installing"
      - run: npm install
      - run: CI=true npm run build
  test:
    docker:
      - image: circleci/node:14.10.1
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
      - run: npm run test --coverage
  scan:
    docker:
      - image: circleci/node:14.10.1
    steps:
      - checkout
      - sonarcloud/scan

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.3

workflows:
  version: 2
  ci:
    jobs:
      - test
      - scan:
          context: SonarCloud
          requires:
            - test
      - build:
          requires:
            - scan
